name: waykup.ch deploy

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Sync
      env:
        dest: 'eebulle@${{secrets.DEPLOY_ADDR}}:/var/www/waykup.ch/public_html/'
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          --exclude=".git" \
          -e 'ssh -p ${{secrets.DEPLOY_PORT}} -i ./deploy_key -o StrictHostKeyChecking=no' \
          ./ ${{env.dest}}
